import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:tracker/common/abstractModel.dart';

class Repository<T extends Model> {
  final user = FirebaseAuth.instance.currentUser;

  Future getEntry<T extends Model>(T dataModel, String collection) async {
    return (await FirebaseFirestore.instance.collection(collection))
        .doc(dataModel.id);
  }

  Future getAllEntries<T extends Model>(String collection) async {
    //TODO: needs to be changed but dart can't accept abstract methods for weird reasons
    User? user = await FirebaseAuth.instance.currentUser;
    return (await FirebaseFirestore.instance
            .collection(collection)
            .where('uid', isEqualTo: user?.uid)
            .get())
        .docs
        .map((item) => Model.fromMap<T>(item.data()))
        .toList();
  }

  Future addEntryWithAutogeneratedId<T extends Model>(
      T dataModel, String collection) async {
    Map<String, dynamic>? data = dataModel.toMap();
    var docID = await FirebaseFirestore.instance
        //   .collection(dataModel.toString().toLowerCase())
        .collection(collection)
        .doc()
        .id;
    data?['uid'] = user?.uid;
    data?['id'] = docID;

    (await FirebaseFirestore.instance
        // .collection(dataModel.toString().toLowerCase())
        .collection(collection)
        .add(data!));
    // (await FirebaseFirestore.instance
    //     .collection(dataModel.runtimeType.toString().toLowerCase())
    //     .doc(docID)
    //     .set(data!));
  }

  // updates an existing entry (missing fields won't be touched on update), document must exist
  Future updateEntryWithId<T extends Model>(
      T dataModel, String collection) async {
    var _querySnapshot = await FirebaseFirestore.instance
        .collection(collection)
        .where("id", isEqualTo: dataModel.id)
        .get();
    if (_querySnapshot.docs.isNotEmpty)
      await _querySnapshot.docs[0].reference.update(dataModel.toMap()!);
  }

  // adds or updates an existing entry (missing fields will be deleted on update!), document will be created if needed
  Future addOrUpdateWithId<T extends Model>(
      T dataModel, String collection) async {
    Map<String, dynamic>? data = dataModel.toMap();
    var docID =
        await FirebaseFirestore.instance.collection(collection).doc().id;
    data?['uid'] = user?.uid;
    data?['id'] = docID;
    var _querySnapshot = await FirebaseFirestore.instance
        .collection(collection)
        .where("id", isEqualTo: dataModel.id)
        .get();
    if (_querySnapshot.docs.isNotEmpty)
      await _querySnapshot.docs[0].reference.set(dataModel.toMap()!);
  }

  // deletes the entry with the given document id
  Future deleteEntry<T extends Model>(T dataModel, String collection) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(dataModel.id)
        .delete();
  }
}
