// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamAxO_H756qQKvbl1LhwdmKzQwaMlW44',
    appId: '1:215782954937:web:5cbfe659958ac15b970868',
    messagingSenderId: '215782954937',
    projectId: 'becove-50654',
    authDomain: 'becove-50654.firebaseapp.com',
    storageBucket: 'becove-50654.appspot.com',
    measurementId: 'G-8BTDF3SNGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYD4hzBZ3Iu4TlemYKBfh5C3cxA7Ihb8',
    appId: '1:215782954937:android:8f1a24cc25b58a54970868',
    messagingSenderId: '215782954937',
    projectId: 'becove-50654',
    storageBucket: 'becove-50654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIK3jOQWaKDeUb0-EMSp8koD62-fBV6XU',
    appId: '1:215782954937:ios:d568d08fc70c139a970868',
    messagingSenderId: '215782954937',
    projectId: 'becove-50654',
    storageBucket: 'becove-50654.appspot.com',
    iosClientId: '215782954937-mki5db38nurtranr6hj73qcefqqn143k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracker',
  );
}
