import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:tracker/features/tracker/models/timer.dart';
import 'package:tracker/features/tracker/tracker_repository.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class TrackerViewModel extends ChangeNotifier {
  // Let's allow the UI to add todos.
  void addTimer() async {
    await TrackerRepository().addEntryWithAutogeneratedId(
        Timer(status: true, start: Timestamp.now()));
    notifyListeners();
  }

  onStartPauseTimer(Timer timer) async {
    if (!timer.status!) {
      addTimer();
    } else {
      timer = timer.copyWith(end: Timestamp.now());
      timer = timer.copyWith(status: false);
      await TrackerRepository().updateEntryWithId(timer);
    }
    notifyListeners();
  }
}

final lastTimer = StreamProvider.autoDispose<Timer>((ref) {
  return TrackerRepository().getLastEntryStream();
});

final timerProvider = ChangeNotifierProvider<TrackerViewModel>((ref) {
  return TrackerViewModel();
});
